### ISSUE TITLE
Add project screenshots

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/spell-bind#36]
Add screenshots of
- Every level
- Every aspect

**Comment by Deepa-chaurasiya01** [comment]
Sir, I want to work on this. But I'm totally new to this, could you please help?

**Comment by kaiwalyakoparkar** [comment]
@Deepa-chaurasiya01 Thanks for your interest. It is very easy. You have to play the game and take screenshots from time to time :slightly_smiling_face: . If you need any help let us know. I will assign it to you

**Comment by Deepa-chaurasiya01** [comment]
Sir, I need help. I got confused as I played all of the game, and I took the screenshots. Like now I've to merge the screenshots folder and push?
Would you mind helping me?

**Comment by Deepa-chaurasiya01** [comment]
Sir, I need help. I got confused as I played all of the game, and I took
the screenshots. Like now I've to merge the screenshots folder and push?
Would you mind helping me?

Thank you
Deepa Chaurasiya

**Comment by kaiwalyakoparkar** [comment]
@Deepa-chaurasiya01 could you please elaborate on the problem?

**Comment by Deepa-chaurasiya01** [comment]
Sure sir, as you said that you have to play the game and take the screenshot from time to time. I did that, but I really don't know how to push the screenshots on GitHub. Or do I've to attach that screenshot folder here? Would you please help me?

**Comment by kaiwalyakoparkar** [comment]
Okay @Deepa-chaurasiya01 if you see the readme there are no screenshots. You can add images to [this folder](https://github.com/kaiwalyakoparkar/spell-bind/tree/main/assets) and then add the images to the readme under **Technologies used** section with the new section name something like **Project preview**. Hope it makes sense :slightly_smiling_face:

**Comment by Deepa-chaurasiya01** [comment]
@kaiwalyakoparkar Sir, I added the project screenshots and updated the README.md.
If any issue with this. please let me know, sir

**Comment by kaiwalyakoparkar** [comment]
Hey @Deepa-chaurasiya01 did you raise a PR for this? (because I cannot see it). You may raise a PR and we can discuss changes (if any) in the PR. :smile:

**Comment by Deepa-chaurasiya01** [comment]
@kaiwalyakoparkar, sir, I did raise a PR for this.

**Comment by kaiwalyakoparkar** [comment]
@Deepa-chaurasiya01 Oops, Sorry for that. Saw it now :sweat_smile:

**Comment by Deepa-chaurasiya01** [comment]
@kaiwalyakoparkar, sir, I added the screenshots and updated the readme.md with the project link, and I also raised PR. Have a look.

**Comment by kaiwalyakoparkar** [comment]
@Deepa-chaurasiya01 I guess I was not clear about the task. Take a look at how screenshots are added in readme https://github.com/kaiwalyakoparkar/sense-hacker . I actually wanted screenshots to be that way

**Comment by Deepa-chaurasiya01** [comment]
Ohh! I am extremely sorry. I'll add the screenshots like that, but I need some time as I have exams.

**Comment by kaiwalyakoparkar** [comment]
@Deepa-chaurasiya01 no worries. Take your time :slightly_smiling_face:

**Comment by Deepa-chaurasiya01** [comment]
@kaiwalyakoparkar  Sir, I added the project screenshots and updated the README.md.
